name: CI Pipeline - All branches

on:
  push:
    branches: [ "**" ]
    branches-ignore: [ "release/*" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ matrix.node-version }}

  test:
    needs: build
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    uses: ./.github/workflows/test.yml
    with:
      node-version: ${{ matrix.node-version }}
    
